[metadata]
name = sl_template
version = 0.0.1
author = Corey Bevan
author_email = corey.bevan@gmail.com
description = retention models to forecast churn
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/CB2702/supervised_learning_template
classifiers =
    Programming Language :: Python :: 3
    Operating System :: OS Independent
    Topic :: Scientific/Engineering :: Information Analysis

[options]
package_dir =
    = packages
packages = find:
python_requires = >=3.12
install_requires = 
    scipy
    numpy
    pandas
    scikit-learn
    matplotlib
    seaborn
    xgboost

[options.package_data]
* = *.csv, *.json

[options.packages.find]
where = packages